import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  backgroundPhoto: {
    flex: 1,
    justifyContent: "flex-end",
  },
  innerContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    paddingBottom: 50,
  },
  updateKeyBoarding: {},
  photoUser: {
    backgroundColor: "#F6F6F6",
    height: 120,
    width: 120,
    borderRadius: 16,
    top: -60,
    left: 128,
    elevation: 10,
    alignItems: "flex-end",
    justifyContent: "flex-end",
    position: "absolute",
  },
  addPhoto: {
    borderWidth: 1,
    borderColor: "#FF6C00",
    backgroundColor: "#fff",
    borderRadius: 50,
    height: 25,
    width: 25,
    top: -14,
    left: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  plus: {
    width: 13,
    height: 13,
  },
  title: {
    fontSize: 30,
    fontFamily: "Roboto-Medium",
    fontWeight: 500,
    marginBottom: 16,
    marginHorizontal: 100,
    alignItems: "center",
    marginTop: 90,
  },
  input: {
    fontFamily: "Roboto-Regular",
    backgroundColor: "#F6F6F6",
    marginTop: 16,
    marginHorizontal: 16,
    height: 50,
    borderWidth: 1,
    borderRadius: 8,
    paddingLeft: 16,
  },
  registerBtn: {
    backgroundColor: "#FF6C00",
    marginHorizontal: 16,
    borderRadius: 100,
    paddingVertical: 16,
    alignItems: "center",
  },
  registerBtnTitle: {
    fontFamily: "Roboto-Regular",
    color: "#fff",
    fontSize: 16,
  },
  anchor: {
    color: "#1B4371",
    fontSize: 16,
    fontFamily: "Roboto-Regular",
    marginTop: 16,
    marginHorizontal: 94,
  },
});
